- id: python-tb-exception
  description: python tracebacks
  start_marker: "^Traceback.*"
  end_marker: "^Exception|Error|InvalidRequest|CalledProcessError|AssertionError:"
